spring.application.name=fleetflow_db
spring.datasource.url=jdbc:mysql://localhost:3307/fleetflow_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=AyoubHadi120
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true



