ALTER TABLE livraison
    MODIFY COLUMN livraisionStatut ENUM('EN_ATTENTE', 'EN_COURS', 'LIVREE', 'ANNULEE') DEFAULT 'EN_ATTENTE';

ALTER TABLE vehicule
    MODIFY COLUMN livraisionStatut ENUM('DISPONIBLE', 'EN_SERVICE', 'EN_PANNE') DEFAULT 'DISPONIBLE';